version: '3.8'
services:
  odin:
    build: 
      context: .
      dockerfile: Dockerfile.odin
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - odin
    environment:
      - VITE_API_URL=http://localhost:3000  
    restart: unless-stopped
    networks:
      - app-network
  ollama-server:
    image: ollama/ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - /mnt/valhalla/ollama-server:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  app-network:
    driver: bridge